-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- local o = vim.o
-- local g = vim.g
-- 
-- o.encoding = "utf-8"
-- o.cursorline = true
-- 
-- g.loaded_netrw = 1
-- g.loaded_netrwPlugin = 1
-- o.termguicolors = true
-- o.guicursor = "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20"
-- 
-- o.filetype = "on"
-- 
-- o.wrap = true
-- 
-- o.textwidth = 72
-- 
-- o.formatoptions = "tcro"
-- o.number = true
-- o.relativenumber = true
-- o.tabstop = 4
-- o.shiftwidth = 2
-- o.expandtab = true
-- --o.listchars="eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:·"
-- o.listchars = "eol:↵,trail:~,tab:>-,nbsp:␣,extends:>,precedes:<,space:·"
-- o.list = true
-- o.autoindent = true
-- o.showtabline = 2
-- o.mouse = n
-- o.undofile = true
-- o.undodir = os.getenv("HOME") .. "/.nvim/.undodir//"
-- o.winbar = "%=%m %f"
